(add-to-list 'load-path (expand-file-name "lisp" user-emacs-directory))
(setq graphic-only-plugins-setting ())
;;----------------------------------------------------------------------------
;; Adjust garbage collection thresholds during startup, and thereafter
;;----------------------------------------------------------------------------
(require 'init-packages)
(require 'init-utils)
(require 'init-core)
(require 'init-ivy)
(require 'init-evil)
(require 'init-prog)
(require 'init-org)
(require 'init-complete)
(require 'init-lsp-mode)
(require 'init-javascript)
(when *is-a-mac*
 (require 'init-agda))
(require 'init-nasm)
(require 'init-treemacs)
(require 'init-ocaml)
(require 'init-c-c++)
(require 'init-python)
(require 'init-common-lisp)
(require 'init-tools)
(require 'init-ui)
;; (when (file-exists-p custom-file)
;;   (load custom-file))
(provide 'init)
