(add-to-list 'load-path (expand-file-name "lisp" user-emacs-directory))

;;----------------------------------------------------------------------------
;; Adjust garbage collection thresholds during startup, and thereafter
;;----------------------------------------------------------------------------
(let ((normal-gc-cons-threshold (* 20 1024 1024))
      (init-gc-cons-threshold (* 128 1024 1024)))
  (setq gc-cons-threshold init-gc-cons-threshold)
  (add-hook 'emacs-startup-hook
            (lambda () (setq gc-cons-threshold normal-gc-cons-threshold))))


(require 'init-base)
(require 'init-utils)
(require 'init-packages)
(require 'init-theme)
(require 'init-doom-modeline)
(require 'init-evil)
(require 'init-ivy)
(require 'init-org)
(require 'init-hungry-delete)
(require 'init-company)
(require 'init-popwin)
(require 'init-imenu)
(require 'init-exec-path)
(require 'init-keybindings)
(require 'init-javascript)
(require 'init-common-lisp)
(when *is-a-mac*
  (require 'init-agda))
(require 'init-nasm)
(require 'init-restart-emacs)
(require 'init-magit)
(require 'init-treemacs)
(require 'init-ocaml)
(require 'init-lsp-mode)
(require 'init-prog)
(require 'init-c-c++)
(require 'init-python)
(require 'init-which-key)
(require 'init-dashboard)
(require 'init-posframe)
(require 'init-rainbow-delimiters)
(require 'init-info-colors)
(require 'init-beacon)
(require 'init-nyan-mode)
(require 'init-command-log)
(require 'init-dired-posframe)
;; (when (file-exists-p custom-file)
;;  (load custom-file))
(provide 'init)
