name: check

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 27.1
          - 26.1
          - 26.2
          - 26.3
        ignore_warnings:
          - false
        include:
          - emacs_version: snapshot
            ignore_warnings: false
    steps:
    - uses: actions/checkout@v2
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: leotaku/elisp-check@master
      with:
        file: dhall-mode.el
        ignore_warnings: ${{ matrix.ignore_warnings }}
        warnings_as_errors: true
